### ISSUE TITLE
Deploy Logs Feature

### ISSUE THREAD

**Issue by kylekarpack** [ndimatteo/sanity-plugin-vercel-deploy#10]
Hi there, I've been doing a little work with a similar plugin (https://github.com/robinpyon/sanity-plugin-dashboard-widget-vercel) and was wondering if adding a dashboard widget and/or a deployment logs table to this plugin would be appreciated? If so, I'd love to submit a pull request.

The dashboard plugin has an issue with sensitive data exposure (see https://github.com/robinpyon/sanity-plugin-dashboard-widget-vercel/issues/2), so I'd love to take advantage of your infrastructure for storing those secrets in Sanity. Please just let me know if you'd accept a PR and if you have any contribution guidelines. Thanks!

**Comment by ndimatteo** [comment]
Hey there @kylekarpack,

I definitely like the idea of a deployment log table and how that could integrate with the current setup!

Perhaps it's something that could function like this– A "view logs" button for each deployment in the current table view, that would open a [Sanity UI dialog](https://www.sanity.io/ui/docs/component/dialog) with the list of associated deployments?

As for a dashboard widget: I don't think that would fit the scope of this project for now. Personally, I like the idea of separating the entire "deployment" aspect to it's own isolated panel, allowing for a more robust UI.

Feel free to fire off a PR for a deployment log table though, I'll happily take a look at that 🤘
