### ISSUE TITLE
Protect Delete Action

### ISSUE THREAD

**Issue by eluce2** [ndimatteo/sanity-plugin-vercel-deploy#24]
Is it possible to restrict the ability to delete a project? I need my clients to be able to deploy on demand, but if they delete the project unintentionally, I have to set it all up for them again.

**Comment by ndimatteo** [comment]
Hey there @eluce2 sorry for the delay,

I'm pleased to say that we were able to add this feature in for the latest V3 release!

You can now disable the delete action when setting up deployments:

![disable-delete-action](https://user-images.githubusercontent.com/737188/214721607-4494fe03-b080-4aa0-90b6-b521644ab892.png)

One thing to note is that the delete action will always remain visible when in development mode, that way you (the developer) can still delete them if necessary.

I hope this helps! 🤘

**Comment by yornaath** [comment]
The delete button isnt showing for me when I am in dev mode

**Comment by ndimatteo** [comment]
hey @yornaath looks like I may have misspoken about the delete action being present in `development`.

You can simply edit the deployment and disable the hide option to bring back the delete action.
