### ISSUE TITLE
Build error when running Sanity

### ISSUE THREAD

**Issue by Rhym** [ndimatteo/sanity-plugin-vercel-deploy#29]
```
/node_modules/sanity-plugin-vercel-deploy/dist/deploy-status.css
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi.js'
```

**Comment by Rhym** [comment]
Fixed by adding `https://www.npmjs.com/package/caniuse-lite` in the dev dependencies as a workaround for the moment.

**Comment by ndimatteo** [comment]
Hey there @Rhym not sure what's causing this error for you, but I just released the official v3 version of this plugin, so I'm going to close this for now given you found a solution and v3 is going to be the main focus moving forward 🤘
