### ISSUE TITLE
Support projects inside vercel teams

### ISSUE THREAD

**Issue by djfarly** [ndimatteo/sanity-plugin-vercel-deploy#3]
Here is one more thing: 

Retrieving the deploy status does not work if the project is inside a vercel team. Basically the api request to `/projects` 404s. As per vercel docs one needs to add `?teamId=` to the request.

I tried the hacky way and put the whole thing `my-project?teamId=my-team-id-423423` into the project name field of this plugin, but that only made the first request working. ;)

For now maybe it would be enough to allow adding a teamId as a setting. Even though that is not user friendly at all since that id is not obvious and needs to be retrieved via api as well.

**Comment by ndimatteo** [comment]
hey @djfarly, great idea!

Going to tag this as a feature request. I think adding another field to supply the team name `slug` would be a good solution here. If supplied it will fetch the team ID from the `/v1/teams?slug` endpoint and send it with the status checks.

**Comment by hdoro** [comment]
@ndimatteo given the solution you outlined above, can I work on the implementation of this? I have a client in need of this feature and I could work on this next week 😄 

(As always, great work with the plugin!)

**Comment by ndimatteo** [comment]
hey @hdoro for sure, I would love the assist! Feel free to give this a stab and submit a PR 🤘

**Comment by ndimatteo** [comment]
@djfarly Team support is now live! ✨

Grab the latest version on [NPM](https://www.npmjs.com/package/sanity-plugin-vercel-deploy)

**Comment by djfarly** [comment]
Awesome! Thanks @hdoro + @ndimatteo 👍
