### ISSUE TITLE
plugin for DigitalOcean

### ISSUE THREAD

**Issue by EricWVGG** [ndimatteo/sanity-plugin-vercel-deploy#31]
Hi Nick

I've been using a hacked-together solution for DigitalOcean deployments for several years now, and finally decided to make a proper plugin.

Yours seemed to do everything I need, so I decided to clone it and modify for DO. Results are here: https://github.com/EricWVGG/sanity-plugin-digitalocean-deploy. It works great!

Do you mind if I release this project on NPM? If so, how can I best credit you and your efforts?

_Many_ thanks,
Eric J

**Comment by EricWVGG** [comment]
btw, I've augmented it with an optional feature to deploy upon hitting the Publish button in Sanity (I like to tell my fellows, "Publish means publish"), I'd be happy to set up a PR for your tool if you'd like that.

**Comment by ndimatteo** [comment]
Hey @EricWVGG,

Sorry for the huge delay in getting back to you 😅 This is awesome though!

Feel free to publish this on NPM, and you credit me however you like. A drop to my github handle would be great 🤘 

Definitely interested in your optional publish to deploy feature. Would love to see how that looks in the UI as well (feel free to email me the details). I just pushed out a Studio V3 version of this plugin, so not sure how feasible it would be for you, but let me know!
