### ISSUE TITLE
Status is not accurately reported when using buildCache=false param

### ISSUE THREAD

**Issue by gpxl** [ndimatteo/sanity-plugin-vercel-deploy#38]
When using [the buildCache param](https://vercel.com/docs/concepts/deployments/deploy-hooks#build-cache), the status will stay in the `Initiated` state forever.

**Comment by gpxl** [comment]
@ndimatteo Could we get a new NPM release with this fix? TY!

**Comment by ndimatteo** [comment]
@gpxl sorry for the delay, had to fix a TS error with your fix in order to publish.

I just pushed up v `3.3.4` so we should be all set now!
