### ISSUE TITLE
Project not found error

### ISSUE THREAD

**Issue by Cardoso-topdev** [ndimatteo/sanity-plugin-vercel-deploy#42]
I created a project on Sanity Deploy by following your readme description.
It deploys if I click on the Deploy button, but not deploy automatically and it shows an error [Project not found]. 
Here is the screenshot of the error.
![image](https://github.com/ndimatteo/sanity-plugin-vercel-deploy/assets/75736745/23e1dea7-0187-4f5b-ad27-cb91a8e709c8)

**Comment by ailadas** [comment]
> ฉันสร้างโปรเจ็กต์บน Sanity Deploy โดยทำตามคำอธิบาย Readme ของคุณ มันปรับใช้ถ้าฉันคลิกที่ปุ่มปรับใช้ แต่ไม่ปรับใช้โดยอัตโนมัติและแสดงข้อผิดพลาด [ไม่พบโครงการ] นี่คือภาพหน้าจอของข้อผิดพลาด ![ภาพ](https://user-images.githubusercontent.com/75736745/242378479-23e1dea7-0187-4f5b-ad27-cb91a8e709c8.png)

**Comment by ailadas** [comment]
> ฉันสร้างโปรเจ็กต์บน Sanity Deploy โดยทำตามคำอธิบาย Readme ของคุณ มันปรับใช้ถ้าฉันคลิกที่ปุ่มปรับใช้ แต่ไม่ปรับใช้โดยอัตโนมัติและแสดงข้อผิดพลาด [ไม่พบโครงการ] นี่คือภาพหน้าจอของข้อผิดพลาด ![ภาพ](https://user-images.githubusercontent.com/75736745/242378479-23e1dea7-0187-4f5b-ad27-cb91a8e709c8.png)
