### ISSUE TITLE
Getting issue with Spacetime

### ISSUE THREAD

**Issue by xavhan** [ndimatteo/sanity-plugin-vercel-deploy#53]
<img width="941" alt="image" src="https://github.com/ndimatteo/sanity-plugin-vercel-deploy/assets/1308790/df875180-2081-4a21-94d1-4536d4fb1505">

I can not display the panel anymore due to some tz issues. 

Is there a setting in sanity config that i can change to avoid this issue in the meantime ?

**Comment by pijusz** [comment]
Seems like Firefox specific issue, at least for me

**Comment by xavhan** [comment]
> Seems like Firefox specific issue, at least for me

I got the issue in Chrome

**Comment by xavhan** [comment]
Issue seems resolved

**Comment by pijusz** [comment]
At least for me it did not get resolved. pushed the PR. Hopefully we get the fix for long time.
