### ISSUE TITLE
Projects missing

### ISSUE THREAD

**Issue by nring** [ndimatteo/sanity-plugin-vercel-deploy#59]
I added two projects for deployment in my Sanity Studio instance and overnight they both disappeared. No new build was triggered and the "Deploy" tab in the Studio was still there. I was just presented with an empty page and the option to add a new project. Is there additional configuration necessary to make sure projects are persisted for longer lengths of time?

**Comment by ndimatteo** [comment]
@nring deploy entries are just documents unde the hood, if they are missing then they were deleted from your dataset (either through the API, CLI, or the Deploy interface).

There's nothing in the core plugin that deletes entries automatically.
