### ISSUE TITLE
A deployment does not refresh my content

### ISSUE THREAD

**Issue by SMccarrick** [ndimatteo/sanity-plugin-vercel-deploy#6]
Hey 

I've just recently started using this package. The package does indeed trigger a new build on vercel but for some reason my newly published content isn't showing up on the new deployment. 

I just wanted to make sure that I haven't missed a step

1. I've published new content in deployed sanity studio 

2. Create a deployment and deploy it

3. Deployment completes but the content on the deployment doesn't

Cheers

**Comment by ndimatteo** [comment]
Hey @SMccarrick !

What does your Vercel project show for deployment logs? And are you using the same sanity dataset and project name between your studio and frontend?

Given the nature of how the deployment plugin works, it's agnostic to the actual Studio you set it up in, as it's simply redeploying the specified Vercel project.

So, if your Vercel project isn't properly hooked up to the sanity project and dataset that you published changes to you won't see any updates reflected when you trigger a deploy.

**Comment by SMccarrick** [comment]
Hey @ndimatteo 

The deployment logs look like a typical build nothing out of the ordinary. My dataset is set to production and my project name is slugified like so `example-name`.

I've just refreshed my tokens and it still isn't working. 

I get that this probably more of an issue with my setup so I'll close for now

Cheers for your help

**Comment by NikkiJonesR** [comment]
@ndimatteo having the same issue as above. The deployment shows correctly in the Vercel Dashboard however the content is updated. When I manually redeploy the sanity vercel deployment again through the dashboard it works.

**Comment by ndimatteo** [comment]
Hey there @NikkiJonesR ! Would you mind going into a bit more detail about what you're experiencing? I'm not sure I follow!

Just to reiterate a few things in case it helps:

1. The Vercel Deploy plugin is agnostic to the studio it's installed in. The plugin only triggers a build of the specified Vercel project. You'll need to make sure the project ID and dataset hooked up to your Vercel project matches with where you're editing.
2. You'll want to always make sure any changes in the associated Sanity project dataset is `published` before triggering a deployment manually from the "Deploy" tab.

Looking forward to hearing more 🤘

**Comment by NikkiJonesR** [comment]
Hi @ndimatteo, yep for sure. I can confirm that the config is setup correctly, and changes are published.

Here's the issue I'm experiencing:
1. Publish a change in the Studio
2. Trigger deploy
3. The content updates on the site as expected
4. Return to the Studio and publish another change
5. Trigger deploy
6. **The content doesn’t update on the site**
7. Return to the Studio and reload the page
8. Trigger deploy
9. The content updates on the site as expected

Hope this helps!

**Comment by ndimatteo** [comment]
Thanks @NikkiJonesR, do you know how the page in question is rendered? is it SSG or ISR by chance? There have been issues raised about ISR pages with Vercel and rebuilds, and I'm wondering if that's a factor here.

If the deploy is triggering every time, and you're seeing it rebuild in Vercel, I'm struggling to see how this plugin would have anything to do with the build itself, as that's all offloaded to Vercel and how your front-end is built.

Curious if there's any other insight into your specific setup that may shine some light on this!

**Comment by NikkiJonesR** [comment]
Hi @ndimatteo the page I was testing on is SSG - nothing fancy we're doing there. It could be a Vercel issue, but it seems peculiar to me that when I do a hard refresh on Sanity it deploys as expected.

**Comment by ansmlc** [comment]
I'm using Hull and supposedly this plugin as well. Same thing is happening. Deploying alone doesn't update the content without doing reloads.

**Comment by ndimatteo** [comment]
@ansmlc check out this answer here, this is likely a cache issue: https://github.com/ndimatteo/sanity-plugin-vercel-deploy/issues/26#issuecomment-1193275567

**Comment by Nateight8** [comment]
Observed the same thing as did @NikkiJonesR with swell.is on nextjs app. Newly published contents don't get refreshed unless I redeploy, any quick fix?

**Comment by ndimatteo** [comment]
@Nateight8 check [#26 (comment)](https://github.com/ndimatteo/sanity-plugin-vercel-deploy/issues/26#issuecomment-1193275567)
