### ISSUE TITLE
Shows incorrect deployment status 🔴

### ISSUE THREAD

**Issue by eivindml** [ndimatteo/sanity-plugin-vercel-deploy#7]
There seems to be some issues with the deployment status in the Sanity dashboard.

## What happens

The build is initiated from Sanity.
<img width="400" alt="Skjermbilde 2021-01-15 kl  22 55 09" src="https://user-images.githubusercontent.com/202450/104782807-20f31300-5785-11eb-93ca-88d6142e527d.png">

The build process is properly starting on Vercel.
<img width="1058" alt="Skjermbilde 2021-01-15 kl  22 56 11" src="https://user-images.githubusercontent.com/202450/104782829-281a2100-5785-11eb-8a98-b1652767a738.png">

The build successfully finishes on Vercel.
<img width="519" alt="Skjermbilde 2021-01-15 kl  22 57 13" src="https://user-images.githubusercontent.com/202450/104782845-2d776b80-5785-11eb-8faf-58954418a03b.png">

Dashboard shows an error status.
<img width="364" alt="Skjermbilde 2021-01-15 kl  22 57 04" src="https://user-images.githubusercontent.com/202450/104782856-323c1f80-5785-11eb-951b-fac618a5cb41.png">

## console.log

<img width="1440" alt="Skjermbilde 2021-01-15 kl  22 55 58" src="https://user-images.githubusercontent.com/202450/104783008-77605180-5785-11eb-85a2-4eb0332214c3.png">

I'm using Safari on macOS.

**Comment by ndimatteo** [comment]
@eivindml interesting, I haven't seen this before. When you created the deployment instance in Sanity, what was the default status _before_ you clicked "Deploy"?

Usually, if you see the "error" state, that means something is not correctly set up with the deployment (either the project name, deploy hook URL, or Vercel token).

**Comment by ndimatteo** [comment]
I also just tested an instance in Safari and am not able to replicate the issue you're having 😬

**Comment by eivindml** [comment]
I added another deployment now, and checked that everything is right, and it's deploying everything correctly, but status is still showing incorrectly. 

I saw there was another issue with support for Vercel teams, and this deployment is also being deployed to a team. I create a new team for each of my clients.

**Comment by ndimatteo** [comment]
@eivindml that would do it! Teams are not supported at the moment due to the different API endpoint requirements.

This is a priority though, so I'll have an update soon!

**Comment by ndimatteo** [comment]
@eivindml Team support is now live! ✨

Grab the latest version on [NPM](https://www.npmjs.com/package/sanity-plugin-vercel-deploy)
